# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicbody', '0025_remove_publicbody_region'),
        ('foirequest', '0032_auto_20181115_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('abitur', 'Abitur')], max_length=100)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicbody.Jurisdiction')),
                ('publicbody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicbody.PublicBody')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_exam.Curriculum')),
                ('foirequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foirequest.FoiRequest')),
            ],
            options={
                'verbose_name': 'Exam Request',
                'verbose_name_plural': 'Exam Requests',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='examrequest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_exam.Subject'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(to='froide_exam.Subject'),
        ),
    ]
