# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'curriculum', 'verbose_name_plural': 'curricula'},
        ),
        migrations.AlterModelOptions(
            name='examrequest',
            options={'ordering': ('-timestamp',), 'verbose_name': 'exam request', 'verbose_name_plural': 'exam requests'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'exam subject', 'verbose_name_plural': 'exam subjects'},
        ),
    ]
