# Generated by Django 2.1.4 on 2018-12-19 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('froide_exam', '0002_auto_20181217_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrequest',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='examrequest',
            name='foirequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foirequest.FoiRequest'),
        ),
        migrations.AlterField(
            model_name='examrequest',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
