# Generated by Django 2.1.4 on 2018-12-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_exam', '0003_auto_20181219_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examrequest',
            old_name='year',
            new_name='start_year',
        ),
        migrations.AddField(
            model_name='examrequest',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
