# Generated by Django 2.1.4 on 2018-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_exam', '0004_auto_20181219_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='legal_status',
            field=models.CharField(choices=[('request', 'Anfragbar'), ('request_not_publish', 'Anfragbar (nicht veröffentlichbar)'), ('public', 'Schon öffentlich'), ('unrequestable', 'Nicht anfragbar')], default='request', max_length=100),
        ),
    ]
