# Generated by Django 2.1.5 on 2019-02-08 10:53

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('publicbody', '0025_remove_publicbody_region'),
        ('froide_exam', '0005_curriculum_legal_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ('name',), 'verbose_name': 'curriculum', 'verbose_name_plural': 'curricula'},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='content_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='content', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='jurisdictions',
            field=models.ManyToManyField(related_name='curriculums', to='publicbody.Jurisdiction'),
        ),
    ]
