# Generated by Django 2.1.5 on 2019-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_exam', '0008_remove_curriculum_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
