# Generated by Django 3.0.8 on 2020-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_exam', '0009_curriculum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='kind',
            field=models.CharField(choices=[('abitur', 'Abitur'), ('realschulabschluss', 'Realschulabschluss'), ('hauptschulabschluss', 'Hauptschulabschluss')], max_length=100),
        ),
    ]
