# Generated by Django 3.0.8 on 2020-12-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0031_publicbody_change_history'),
        ('froide_exam', '0010_auto_20201218_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('legal_status', models.CharField(choices=[('request', 'Anfragbar'), ('request_not_publish', 'Anfragbar (nicht veröffentlichbar)'), ('public', 'Schon öffentlich'), ('unrequestable', 'Nicht anfragbar')], default='request', max_length=100)),
                ('publicbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicbody.PublicBody')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_exam.State'),
        ),
    ]
