# Generated by Django 3.1.6 on 2021-03-16 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('froide_exam', '0014_require_curriculum_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateCopy',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(
                    default=uuid.uuid4, editable=False, db_index=True)),
            ],
            options={
                'verbose_name': 'private copy',
                'verbose_name_plural': 'private copies',
            },
        ),
    ]
