# Generated by Django 4.2.16 on 2025-03-12 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.FILINGCABINET_DOCUMENT_MODEL),
        ("froide_exam", "0016_remove_legacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="examrequest",
            name="documents",
            field=models.ManyToManyField(
                to=settings.FILINGCABINET_DOCUMENT_MODEL,
                blank=True,
            ),
        ),
    ]
