# Generated by Django 4.2.16 on 2025-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_exam", "0016_remove_legacy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="legal_status",
            field=models.CharField(
                choices=[
                    ("request", "Requestable"),
                    ("request_not_publish", "Requestable (not publishable)"),
                    ("public", "Already public"),
                    ("unrequestable", "Not requestable"),
                ],
                default="request",
                max_length=100,
            ),
        ),
    ]
