# Generated by Django 5.2.15 on 2026-09-07 13:24

from datetime import date

from django.db import migrations, models


def migrate_years(apps, schema_editor):
    ExamRequest = apps.get_model("froide_exam", "ExamRequest")
    Curriculum = apps.get_model("froide_exam", "Curriculum")

    for Model in (ExamRequest, Curriculum):
        updates = []
        objects = Model.objects.all()
        for obj in objects:
            if obj.start_year_date:
                obj.start_year = obj.start_year_date.year
            if obj.end_year_date:
                obj.end_year = obj.end_year_date.year

            if obj.start_year_date or obj.end_year_date:
                updates.append(obj)

        Model.objects.bulk_update(updates, ["start_year", "end_year"])


def reverse_migrate_years(apps, schema_editor):
    ExamRequest = apps.get_model("froide_exam", "ExamRequest")
    Curriculum = apps.get_model("froide_exam", "Curriculum")

    for Model in (ExamRequest, Curriculum):
        updates = []
        objects = Model.objects.all()
        for obj in objects:
            if obj.start_year:
                obj.start_year_date = date(obj.start_year, 1, 1)
            if obj.end_year:
                obj.end_year_date = date(obj.end_year, 12, 31)

            if obj.start_year or obj.end_year:
                updates.append(obj)

        Model.objects.bulk_update(updates, ["start_year_date", "end_year_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("froide_exam", "0017_examrequest_documents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curriculum",
            old_name="start_year",
            new_name="start_year_date",
        ),
        migrations.RenameField(
            model_name="curriculum",
            old_name="end_year",
            new_name="end_year_date",
        ),
        migrations.RenameField(
            model_name="examrequest",
            old_name="start_year",
            new_name="start_year_date",
        ),
        migrations.RenameField(
            model_name="examrequest",
            old_name="end_year",
            new_name="end_year_date",
        ),
        migrations.AddField(
            model_name="curriculum",
            name="end_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="start_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examrequest",
            name="end_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examrequest",
            name="start_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_years, reverse_migrate_years),
        migrations.AlterField(
            model_name="examrequest",
            name="start_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="end_year_date",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="start_year_date",
        ),
        migrations.RemoveField(
            model_name="examrequest",
            name="end_year_date",
        ),
        migrations.RemoveField(
            model_name="examrequest",
            name="start_year_date",
        ),
    ]
