# Generated by Django 5.2.15 on 2026-09-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_exam", "0018_date_to_int"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examrequest",
            name="curriculum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="froide_exam.curriculum"
            ),
        ),
        migrations.AlterField(
            model_name="examrequest",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="froide_exam.subject",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="legal_status",
            field=models.CharField(
                choices=[
                    ("request", "Requestable"),
                    ("request_not_publish", "Requestable (not publishable)"),
                    ("public", "Already public"),
                    ("unrequestable", "Not requestable"),
                ],
                default="request",
                max_length=100,
            ),
        ),
    ]
